spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: secret

  data:
    redis:
      port: 6379
      database: 0
      host: redis
backup:
  directory: C:\Users\Егор\IdeaProjects\DB_Project_Back\backups
  dbName: mydb

jwt:
  access-token-expiration:
    3600000 # 1 час для access токена
  refresh-token-expiration:
    604800000 # 7 дней для refresh токена